package com.tcmkb.service.impl;
import com.tcmkb.service.AsthmaEvaluationDiagnosisTreatmentService;
public class AsthmaEvaluationDiagnosisTreatmentServiceImpl implements AsthmaEvaluationDiagnosisTreatmentService{

}