package com.tcmkb.service.impl;
import com.tcmkb.service.AsthmaTraditionalChineseMedicineService;
public class AsthmaTraditionalChineseMedicineServiceImpl implements AsthmaTraditionalChineseMedicineService{

}