package com.tcmkb.service.impl;
import com.tcmkb.service.AsthmaCharacteristicTreatmentService;
public class AsthmaCharacteristicTreatmentServiceImpl implements AsthmaCharacteristicTreatmentService{

}