package com.tcmkb.service.impl;
import com.tcmkb.service.GastritisDiagnosisTreatmentStandardService;
public class GastritisDiagnosisTreatmentStandardServiceImpl implements GastritisDiagnosisTreatmentStandardService{

}