package com.tcmkb.service.impl;
import com.tcmkb.service.GastritisSystemEvaluationCopy1Service;
public class GastritisSystemEvaluationCopy1ServiceImpl implements GastritisSystemEvaluationCopy1Service{

}