package com.tcmkb.service.impl;
import com.tcmkb.service.GastritisSystemEvaluationCopyService;
public class GastritisSystemEvaluationCopyServiceImpl implements GastritisSystemEvaluationCopyService{

}